DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = robot_driver

TARGETDIRS += ../../platform

all: $(CONTIKI_PROJECT)

CONTIKI = ../../../../contiki
CONTIKI_WITH_RIME = 1

include $(CONTIKI)/Makefile.include
